### PR TITLE
⭐️ add new github community to readme

### PR DESCRIPTION
**Pull request by chris-rock**
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>

### CODE REVIEW

**Comment by chris-rock** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chris-rock** [comment]
recheck

**Comment by chris-rock** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chris-rock** [comment]
I have read the Mondoo CLA Document and I hereby sign the CLA

**Review by benr — APPROVED** [review]

**Pull request merged**
